accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/',views.signup, name='signup'),
    url(r'^login/',views.loginview, name='login'),


]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/',views.create, name='create'),


]

redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name='home'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                return render(request, 'accounts/signup.html')
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request,user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords did not match'})
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return render(request, 'accounts/login.html', {'error': 'Login successful!'})
        else:
            return render(request, 'accounts/login.html', {'error': 'Username and passwords did not match'})
    else:
        return render(request, 'accounts/login.html')

posts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from . import models
# Create your views here.


@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = models.Post()
            post.title = request.POST['title']
            post.url = request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return render(request, 'posts/home.html')

        else:
            return render(request, 'posts/create.html', {'error': 'Error: You must include a title and a url'})

    else:
        return render(request, 'posts/create.html')

def home(request):
    return render(request, 'posts/home.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Login!</h1>

    {% if error %}
    {{ error }}
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}

      {% if request.GET.next %}
        <input type='hidden' name='next' value= {{ request.GET.next }} />
      {% endif %}
      
      Username:
      <br>
      <input type="text" name="username" value="" placeholder="user name">
      <br>
      Password:
      <input type="password" name="password" value="">
      <input type="submit" value="singup">
    </form>
  </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Sign up!</h1>

    {% if error %}
    {{ error }}
    {% endif %}
    
    <form action="{% url 'signup' %}" method="POST">
      {% csrf_token %}
      Username:
      <input type="text" name="username" value="" placeholder="user name">
      Password:
      <input type="password" name="password1" value="">
      Confirm password:
      <input type="password" name="password2" value="">
      <input type="submit" value="singup">
    </form>
  </body>
</html>

posts/templates/posts/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>new post!</h1>

    {% if error %}
    {{ error }}
    {% endif %}

    <form action="{% url 'posts:create' %}" method="POST">
      {% csrf_token %}



      Title:
      <br>
      <input type="text" name="title" value="" placeholder="new post">
      <br>
      URL:
      <input type="text" name="url" value="">
      <input type="submit" value="Post">
    </form>
  </body>
</html>

posts/templates/posts/home.html
HOME page